-- Days 8–30 for interview, conversation, and bundle.
insert into public.course_days (course_id, day_number, title, theme) values
  ('interview', 8, 'A typical work day', 'Talk about your work'),
  ('interview', 9, 'A project you owned', 'Talk about your work'),
  ('interview', 10, 'Working with a team', 'Talk about your work'),
  ('interview', 11, 'A tight deadline', 'Talk about your work'),
  ('interview', 12, 'Tools and process', 'Talk about your work'),
  ('interview', 13, 'What you learned', 'Talk about your work'),
  ('interview', 14, 'Week 2 review — mini mock', 'Talk about your work'),
  ('interview', 15, 'Your strengths', 'The classic questions'),
  ('interview', 16, 'A weakness you are improving', 'The classic questions'),
  ('interview', 17, 'Why this company', 'The classic questions'),
  ('interview', 18, 'A mistake you learned from', 'The classic questions'),
  ('interview', 19, 'Five years from now', 'The classic questions'),
  ('interview', 20, 'Notice period and joining', 'The classic questions'),
  ('interview', 21, 'Week 3 review — mini mock', 'The classic questions'),
  ('interview', 22, 'An unexpected question', 'Pressure-proof'),
  ('interview', 23, 'Disagreeing politely', 'Pressure-proof'),
  ('interview', 24, 'Feedback and criticism', 'Pressure-proof'),
  ('interview', 25, 'Two offers', 'Pressure-proof'),
  ('interview', 26, 'A gap or a slow start', 'Pressure-proof'),
  ('interview', 27, 'Why you, not someone else', 'Pressure-proof'),
  ('interview', 28, 'Mock round — yourself', 'Pressure-proof'),
  ('interview', 29, 'Mock round — a story', 'Pressure-proof'),
  ('interview', 30, 'Final mock', 'Pressure-proof'),
  ('conversation', 8, 'This week''s plans', 'Plans & stories'),
  ('conversation', 9, 'A childhood story', 'Plans & stories'),
  ('conversation', 10, 'A time you helped someone', 'Plans & stories'),
  ('conversation', 11, 'A trip you want', 'Plans & stories'),
  ('conversation', 12, 'A funny mistake', 'Plans & stories'),
  ('conversation', 13, 'Your people', 'Plans & stories'),
  ('conversation', 14, 'Week 2 review — a story', 'Plans & stories'),
  ('conversation', 15, 'Phone vs meeting people', 'Opinions & reactions'),
  ('conversation', 16, 'Working from home', 'Opinions & reactions'),
  ('conversation', 17, 'An app you use', 'Opinions & reactions'),
  ('conversation', 18, 'Something you heard', 'Opinions & reactions'),
  ('conversation', 19, 'Advice for a friend', 'Opinions & reactions'),
  ('conversation', 20, 'Your city, your view', 'Opinions & reactions'),
  ('conversation', 21, 'Week 3 review — your take', 'Opinions & reactions'),
  ('conversation', 22, 'In a shop', 'Real-world situations'),
  ('conversation', 23, 'A polite complaint', 'Real-world situations'),
  ('conversation', 24, 'Calling a clinic', 'Real-world situations'),
  ('conversation', 25, 'Meeting someone new', 'Real-world situations'),
  ('conversation', 26, 'Giving directions', 'Real-world situations'),
  ('conversation', 27, 'Talking about money', 'Real-world situations'),
  ('conversation', 28, 'Small talk at work', 'Real-world situations'),
  ('conversation', 29, 'A misunderstanding', 'Real-world situations'),
  ('conversation', 30, 'Final free talk', 'Real-world situations'),
  ('bundle', 8, 'A typical work day', 'The complete path — Week 2'),
  ('bundle', 9, 'A project you owned', 'The complete path — Week 2'),
  ('bundle', 10, 'This week''s plans', 'The complete path — Week 2'),
  ('bundle', 11, 'Working with a team', 'The complete path — Week 2'),
  ('bundle', 12, 'A trip you want', 'The complete path — Week 2'),
  ('bundle', 13, 'A tight deadline', 'The complete path — Week 2'),
  ('bundle', 14, 'Mixed review — work and stories', 'The complete path — Week 2'),
  ('bundle', 15, 'Your strengths', 'The complete path — Week 3'),
  ('bundle', 16, 'A weakness you are improving', 'The complete path — Week 3'),
  ('bundle', 17, 'Phone vs meeting people', 'The complete path — Week 3'),
  ('bundle', 18, 'Why this company', 'The complete path — Week 3'),
  ('bundle', 19, 'Advice for a friend', 'The complete path — Week 3'),
  ('bundle', 20, 'A mistake you learned from', 'The complete path — Week 3'),
  ('bundle', 21, 'Mixed review — opinions and classics', 'The complete path — Week 3'),
  ('bundle', 22, 'An unexpected question', 'The complete path — Week 4'),
  ('bundle', 23, 'In a shop', 'The complete path — Week 4'),
  ('bundle', 24, 'Disagreeing politely', 'The complete path — Week 4'),
  ('bundle', 25, 'Calling a clinic', 'The complete path — Week 4'),
  ('bundle', 26, 'Why you, not someone else', 'The complete path — Week 4'),
  ('bundle', 27, 'A misunderstanding', 'The complete path — Week 4'),
  ('bundle', 28, 'Mock round — yourself', 'The complete path — Week 4'),
  ('bundle', 29, 'Final free talk', 'The complete path — Week 4'),
  ('bundle', 30, 'Final mixed mock', 'The complete path — Week 4')
on conflict (course_id, day_number) do update
  set title = excluded.title,
      theme = excluded.theme;

insert into public.questions (course_day_id, position, prompt, hint)
select d.id, q.position, q.prompt, q.hint
from (
  values
    ('interview', 8, 1, 'Walk me through a normal day at work or college.', 'Usually my day starts with ___.'),
    ('interview', 8, 2, 'What part of the day is hardest, and why?', 'The hardest part is ___.'),
    ('interview', 8, 3, 'Who do you work with most, and how do you help each other?', 'Usually my day starts with ___.'),
    ('interview', 9, 1, 'Tell me about a project you owned from start to finish.', 'I owned a project where ___.'),
    ('interview', 9, 2, 'What was the goal of that project?', 'The goal was ___.'),
    ('interview', 9, 3, 'What would you do differently next time?', 'I owned a project where ___.'),
    ('interview', 10, 1, 'Tell me about a time you worked in a team.', 'In my team I was responsible for ___.'),
    ('interview', 10, 2, 'What was your role in that team?', 'When we disagreed, I ___.'),
    ('interview', 10, 3, 'How did you handle a disagreement?', 'In my team I was responsible for ___.'),
    ('interview', 11, 1, 'Tell me about a time the deadline was very tight.', 'The deadline was tight, so I ___.'),
    ('interview', 11, 2, 'What did you do first?', 'In the end, we ___.'),
    ('interview', 11, 3, 'How did it end?', 'The deadline was tight, so I ___.'),
    ('interview', 12, 1, 'What tools do you use in your work or studies?', 'I usually use ___ to ___.'),
    ('interview', 12, 2, 'How do you keep track of tasks?', 'To stay organised I ___.'),
    ('interview', 12, 3, 'How do you make sure work is accurate?', 'I usually use ___ to ___.'),
    ('interview', 13, 1, 'What is the most useful thing you learned at work or in training?', 'The most useful thing I learned was ___.'),
    ('interview', 13, 2, 'Who taught you that?', 'I use it when I ___.'),
    ('interview', 13, 3, 'How do you use it now?', 'The most useful thing I learned was ___.'),
    ('interview', 14, 1, 'Walk me through a project you are proud of.', 'I am proud of a project where ___.'),
    ('interview', 14, 2, 'What was your responsibility?', 'I am proud of a project where ___.'),
    ('interview', 14, 3, 'What did you learn from working with others?', 'I am proud of a project where ___.'),
    ('interview', 15, 1, 'What is your biggest strength?', 'My biggest strength is ___.'),
    ('interview', 15, 2, 'Give me one example of that strength at work or college.', 'For example, once I ___.'),
    ('interview', 15, 3, 'How would a teammate describe you?', 'My biggest strength is ___.'),
    ('interview', 16, 1, 'What is one thing you are trying to improve?', 'I am working on ___.'),
    ('interview', 16, 2, 'What are you doing to get better?', 'To get better I ___.'),
    ('interview', 16, 3, 'How will you know you have improved?', 'I am working on ___.'),
    ('interview', 17, 1, 'Why do you want to work with us?', 'I want to work here because ___.'),
    ('interview', 17, 2, 'What do you know about this role?', 'In the first three months I hope to ___.'),
    ('interview', 17, 3, 'What would you like to learn here in the first three months?', 'I want to work here because ___.'),
    ('interview', 18, 1, 'Tell me about a mistake you made.', 'I once made a mistake when ___.'),
    ('interview', 18, 2, 'What did you do after you noticed it?', 'After that I started to ___.'),
    ('interview', 18, 3, 'What changed in how you work after that?', 'I once made a mistake when ___.'),
    ('interview', 19, 1, 'Where do you see yourself in five years?', 'In five years I hope to ___.'),
    ('interview', 19, 2, 'What skill do you want to be known for?', 'I want to be known for ___.'),
    ('interview', 19, 3, 'What kind of team do you want to work in?', 'In five years I hope to ___.'),
    ('interview', 20, 1, 'When can you join if we make an offer?', 'I can join in ___.'),
    ('interview', 20, 2, 'Are you interviewing anywhere else?', 'One question I have is ___.'),
    ('interview', 20, 3, 'What questions do you have for me?', 'I can join in ___.'),
    ('interview', 21, 1, 'What is your biggest strength?', 'My biggest strength is ___.'),
    ('interview', 21, 2, 'Why this role?', 'My biggest strength is ___.'),
    ('interview', 21, 3, 'Tell me about a mistake you learned from.', 'My biggest strength is ___.'),
    ('interview', 22, 1, 'Tell me something that is not on your resume.', 'One thing people don''t see on my resume is ___.'),
    ('interview', 22, 2, 'What do you do to stay calm under pressure?', 'When I feel pressure I ___.'),
    ('interview', 22, 3, 'If you had a free afternoon, how would you spend it?', 'One thing people don''t see on my resume is ___.'),
    ('interview', 23, 1, 'Tell me about a time you disagreed with a teacher, manager, or teammate.', 'I disagreed when ___.'),
    ('interview', 23, 2, 'How did you say it without making it personal?', 'I said it by ___.'),
    ('interview', 23, 3, 'What happened after that?', 'I disagreed when ___.'),
    ('interview', 24, 1, 'Tell me about a time someone criticised your work.', 'Someone once told me ___.'),
    ('interview', 24, 2, 'What did you do with that feedback?', 'I used that to ___.'),
    ('interview', 24, 3, 'What did you change the next time?', 'Someone once told me ___.'),
    ('interview', 25, 1, 'If you had two job offers, how would you choose?', 'I would choose based on ___.'),
    ('interview', 25, 2, 'What matters more to you: learning or salary, and why?', 'I would stay if ___.'),
    ('interview', 25, 3, 'What would make you stay in a job for two years?', 'I would choose based on ___.'),
    ('interview', 26, 1, 'Have you ever had a gap in studies or work? What did you do then?', 'During that time I ___.'),
    ('interview', 26, 2, 'How do you explain a slow start on a new task?', 'To learn faster I ___.'),
    ('interview', 26, 3, 'What helps you learn a new job faster?', 'During that time I ___.'),
    ('interview', 27, 1, 'Why should we hire you and not the next person?', 'You should hire me because ___.'),
    ('interview', 27, 2, 'What can you start helping with in week one?', 'In week one I can ___.'),
    ('interview', 27, 3, 'What is one promise you can keep if we hire you?', 'You should hire me because ___.'),
    ('interview', 28, 1, 'Tell me about yourself in 45 seconds.', 'To introduce myself, ___.'),
    ('interview', 28, 2, 'What are you good at?', 'To introduce myself, ___.'),
    ('interview', 28, 3, 'Why this field?', 'To introduce myself, ___.'),
    ('interview', 29, 1, 'Tell me about a challenge you overcame.', 'The challenge was ___.'),
    ('interview', 29, 2, 'What did you do, step by step?', 'I did ___, and the result was ___.'),
    ('interview', 29, 3, 'What was the result?', 'The challenge was ___.'),
    ('interview', 30, 1, 'Introduce yourself.', 'In short, I can ___.'),
    ('interview', 30, 2, 'Tell me about a project you owned.', 'In short, I can ___.'),
    ('interview', 30, 3, 'Why should we hire you, in two sentences?', 'In short, I can ___.'),
    ('conversation', 8, 1, 'What are your plans for this week?', 'This week I plan to ___.'),
    ('conversation', 8, 2, 'What is one thing you must finish?', 'I must finish ___.'),
    ('conversation', 8, 3, 'What are you looking forward to?', 'This week I plan to ___.'),
    ('conversation', 9, 1, 'Tell me a small story from your childhood.', 'When I was younger, ___.'),
    ('conversation', 9, 2, 'Who was with you?', 'I still remember it because ___.'),
    ('conversation', 9, 3, 'Why do you still remember it?', 'When I was younger, ___.'),
    ('conversation', 10, 1, 'Tell me about a time you helped someone.', 'I helped someone when ___.'),
    ('conversation', 10, 2, 'What did they need?', 'They needed ___.'),
    ('conversation', 10, 3, 'How did it feel afterwards?', 'I helped someone when ___.'),
    ('conversation', 11, 1, 'If you could travel anywhere next year, where would you go?', 'I would go to ___.'),
    ('conversation', 11, 2, 'Who would you take with you?', 'On the first day I would ___.'),
    ('conversation', 11, 3, 'What would you do on the first day?', 'I would go to ___.'),
    ('conversation', 12, 1, 'Tell me about a funny mistake you made.', 'I once made a funny mistake when ___.'),
    ('conversation', 12, 2, 'What happened next?', 'Now I laugh because ___.'),
    ('conversation', 12, 3, 'Do you laugh about it now?', 'I once made a funny mistake when ___.'),
    ('conversation', 13, 1, 'Who do you spend most evenings with?', 'I usually spend evenings with ___.'),
    ('conversation', 13, 2, 'Tell me about one person who matters to you.', 'They matter to me because ___.'),
    ('conversation', 13, 3, 'What do you usually talk about?', 'I usually spend evenings with ___.'),
    ('conversation', 14, 1, 'Tell me about last weekend as a short story.', 'Last weekend I ___.'),
    ('conversation', 14, 2, 'What was the best moment?', 'The best moment was ___.'),
    ('conversation', 14, 3, 'What will you do differently next weekend?', 'Last weekend I ___.'),
    ('conversation', 15, 1, 'Do you prefer chatting on the phone or meeting in person? Why?', 'I prefer ___ because ___.'),
    ('conversation', 15, 2, 'When is a message better than a call?', 'A message is better when ___.'),
    ('conversation', 15, 3, 'How do you start a conversation with someone new?', 'I prefer ___ because ___.'),
    ('conversation', 16, 1, 'Would you rather work from home or go to an office? Why?', 'I would rather ___ because ___.'),
    ('conversation', 16, 2, 'What is hard about each option?', 'To stay focused I ___.'),
    ('conversation', 16, 3, 'How do you stay focused?', 'I would rather ___ because ___.'),
    ('conversation', 17, 1, 'What app do you use every day, and why?', 'I use ___ every day because ___.'),
    ('conversation', 17, 2, 'How does it help you?', 'I wish it could ___.'),
    ('conversation', 17, 3, 'What is one thing you wish it did better?', 'I use ___ every day because ___.'),
    ('conversation', 18, 1, 'Tell me about a piece of news or a story that interested you this week.', 'I heard about ___.'),
    ('conversation', 18, 2, 'Why did it catch your attention?', 'I think ___.'),
    ('conversation', 18, 3, 'What is your opinion on it?', 'I heard about ___.'),
    ('conversation', 19, 1, 'A friend is nervous about speaking English. What would you tell them?', 'I would tell them ___.'),
    ('conversation', 19, 2, 'What helped you personally?', 'They should start with ___.'),
    ('conversation', 19, 3, 'What should they practise first?', 'I would tell them ___.'),
    ('conversation', 20, 1, 'If you could change one thing in your city, what would it be?', 'I would change ___.'),
    ('conversation', 20, 2, 'Who would it help?', 'It would help ___.'),
    ('conversation', 20, 3, 'What small thing could people do this week?', 'I would change ___.'),
    ('conversation', 21, 1, 'Give your opinion on working from home.', 'In my view, ___.'),
    ('conversation', 21, 2, 'Tell me about an app you like.', 'In my view, ___.'),
    ('conversation', 21, 3, 'What advice would you give a nervous speaker?', 'In my view, ___.'),
    ('conversation', 22, 1, 'You cannot find something in a shop. What do you say to the staff?', 'Excuse me, could you help me find ___?'),
    ('conversation', 22, 2, 'They show you the wrong item. What do you say?', 'I was looking for ___.'),
    ('conversation', 22, 3, 'How do you thank them and leave?', 'Excuse me, could you help me find ___?'),
    ('conversation', 23, 1, 'Your food order is wrong. What do you say?', 'Sorry, I ordered ___, but I received ___.'),
    ('conversation', 23, 2, 'They offer to fix it. How do you reply?', 'Thank you, that would help.'),
    ('conversation', 23, 3, 'How do you keep it calm and clear?', 'Sorry, I ordered ___, but I received ___.'),
    ('conversation', 24, 1, 'You need to book an appointment. What do you say first?', 'Hello, I would like to book an appointment.'),
    ('conversation', 24, 2, 'They ask what the problem is. How do you explain it simply?', 'I am free on ___ at ___.'),
    ('conversation', 24, 3, 'How do you confirm the day and time?', 'Hello, I would like to book an appointment.'),
    ('conversation', 25, 1, 'You are at a gathering and you know nobody. How do you start talking?', 'Hi, I don''t think we have met. I''m ___.'),
    ('conversation', 25, 2, 'They ask what you do. How do you answer in one sentence?', 'It was nice talking to you.'),
    ('conversation', 25, 3, 'How do you end the chat politely?', 'Hi, I don''t think we have met. I''m ___.'),
    ('conversation', 26, 1, 'Someone asks how to reach the station from your area. What do you say?', 'Go straight till you see ___, then ___.'),
    ('conversation', 26, 2, 'What landmark would you mention?', 'Does that make sense?'),
    ('conversation', 26, 3, 'How do you check they understood?', 'Go straight till you see ___, then ___.'),
    ('conversation', 27, 1, 'A friend asks to split a bill. What do you say?', 'Shall we split it?'),
    ('conversation', 27, 2, 'The amount looks high. How do you ask, politely?', 'Could you show me the amount once?'),
    ('conversation', 27, 3, 'How do you settle it?', 'Shall we split it?'),
    ('conversation', 28, 1, 'A colleague asks about your weekend. What do you say?', 'My weekend was ___. How was yours?'),
    ('conversation', 28, 2, 'They look busy. How do you keep it short?', 'I''ll let you get back to it.'),
    ('conversation', 28, 3, 'How do you ask how they are doing?', 'My weekend was ___. How was yours?'),
    ('conversation', 29, 1, 'Someone misunderstood what you said. How do you clear it up?', 'Sorry, what I meant was ___.'),
    ('conversation', 29, 2, 'What do you say if it was your mistake?', 'Thanks for checking — let''s ___.'),
    ('conversation', 29, 3, 'How do you move the conversation forward?', 'Sorry, what I meant was ___.'),
    ('conversation', 30, 1, 'Pick a real situation from this week and talk for one minute.', 'This week I had to ___.'),
    ('conversation', 30, 2, 'What did you say, and what do you wish you had said?', 'Next time I will say ___.'),
    ('conversation', 30, 3, 'What will you try next time?', 'This week I had to ___.'),
    ('bundle', 8, 1, 'Walk me through a normal day at work or college.', 'Usually my day starts with ___.'),
    ('bundle', 8, 2, 'What part of the day is hardest, and why?', 'The hardest part is ___.'),
    ('bundle', 8, 3, 'Who do you work with most, and how do you help each other?', 'Usually my day starts with ___.'),
    ('bundle', 9, 1, 'Tell me about a project you owned from start to finish.', 'I owned a project where ___.'),
    ('bundle', 9, 2, 'What was the goal of that project?', 'The goal was ___.'),
    ('bundle', 9, 3, 'What would you do differently next time?', 'I owned a project where ___.'),
    ('bundle', 10, 1, 'What are your plans for this week?', 'This week I plan to ___.'),
    ('bundle', 10, 2, 'What is one thing you must finish?', 'I must finish ___.'),
    ('bundle', 10, 3, 'What are you looking forward to?', 'This week I plan to ___.'),
    ('bundle', 11, 1, 'Tell me about a time you worked in a team.', 'In my team I was responsible for ___.'),
    ('bundle', 11, 2, 'What was your role in that team?', 'When we disagreed, I ___.'),
    ('bundle', 11, 3, 'How did you handle a disagreement?', 'In my team I was responsible for ___.'),
    ('bundle', 12, 1, 'If you could travel anywhere next year, where would you go?', 'I would go to ___.'),
    ('bundle', 12, 2, 'Who would you take with you?', 'On the first day I would ___.'),
    ('bundle', 12, 3, 'What would you do on the first day?', 'I would go to ___.'),
    ('bundle', 13, 1, 'Tell me about a time the deadline was very tight.', 'The deadline was tight, so I ___.'),
    ('bundle', 13, 2, 'What did you do first?', 'In the end, we ___.'),
    ('bundle', 13, 3, 'How did it end?', 'The deadline was tight, so I ___.'),
    ('bundle', 14, 1, 'Walk me through a project you owned.', 'I am proud of a project where ___.'),
    ('bundle', 14, 2, 'What did you do last weekend?', 'I am proud of a project where ___.'),
    ('bundle', 14, 3, 'What did you learn from working with others?', 'I am proud of a project where ___.'),
    ('bundle', 15, 1, 'What is your biggest strength?', 'My biggest strength is ___.'),
    ('bundle', 15, 2, 'Give me one example of that strength at work or college.', 'For example, once I ___.'),
    ('bundle', 15, 3, 'How would a teammate describe you?', 'My biggest strength is ___.'),
    ('bundle', 16, 1, 'What is one thing you are trying to improve?', 'I am working on ___.'),
    ('bundle', 16, 2, 'What are you doing to get better?', 'To get better I ___.'),
    ('bundle', 16, 3, 'How will you know you have improved?', 'I am working on ___.'),
    ('bundle', 17, 1, 'Do you prefer chatting on the phone or meeting in person? Why?', 'I prefer ___ because ___.'),
    ('bundle', 17, 2, 'When is a message better than a call?', 'A message is better when ___.'),
    ('bundle', 17, 3, 'How do you start a conversation with someone new?', 'I prefer ___ because ___.'),
    ('bundle', 18, 1, 'Why do you want to work with us?', 'I want to work here because ___.'),
    ('bundle', 18, 2, 'What do you know about this role?', 'In the first three months I hope to ___.'),
    ('bundle', 18, 3, 'What would you like to learn here in the first three months?', 'I want to work here because ___.'),
    ('bundle', 19, 1, 'A friend is nervous about speaking English. What would you tell them?', 'I would tell them ___.'),
    ('bundle', 19, 2, 'What helped you personally?', 'They should start with ___.'),
    ('bundle', 19, 3, 'What should they practise first?', 'I would tell them ___.'),
    ('bundle', 20, 1, 'Tell me about a mistake you made.', 'I once made a mistake when ___.'),
    ('bundle', 20, 2, 'What did you do after you noticed it?', 'After that I started to ___.'),
    ('bundle', 20, 3, 'What changed in how you work after that?', 'I once made a mistake when ___.'),
    ('bundle', 21, 1, 'What is your biggest strength?', 'My biggest strength is ___.'),
    ('bundle', 21, 2, 'Would you rather work from home or go to an office?', 'My biggest strength is ___.'),
    ('bundle', 21, 3, 'Tell me about a mistake you learned from.', 'My biggest strength is ___.'),
    ('bundle', 22, 1, 'Tell me something that is not on your resume.', 'One thing people don''t see on my resume is ___.'),
    ('bundle', 22, 2, 'What do you do to stay calm under pressure?', 'When I feel pressure I ___.'),
    ('bundle', 22, 3, 'If you had a free afternoon, how would you spend it?', 'One thing people don''t see on my resume is ___.'),
    ('bundle', 23, 1, 'You cannot find something in a shop. What do you say to the staff?', 'Excuse me, could you help me find ___?'),
    ('bundle', 23, 2, 'They show you the wrong item. What do you say?', 'I was looking for ___.'),
    ('bundle', 23, 3, 'How do you thank them and leave?', 'Excuse me, could you help me find ___?'),
    ('bundle', 24, 1, 'Tell me about a time you disagreed with a teacher, manager, or teammate.', 'I disagreed when ___.'),
    ('bundle', 24, 2, 'How did you say it without making it personal?', 'I said it by ___.'),
    ('bundle', 24, 3, 'What happened after that?', 'I disagreed when ___.'),
    ('bundle', 25, 1, 'You need to book an appointment. What do you say first?', 'Hello, I would like to book an appointment.'),
    ('bundle', 25, 2, 'They ask what the problem is. How do you explain it simply?', 'I am free on ___ at ___.'),
    ('bundle', 25, 3, 'How do you confirm the day and time?', 'Hello, I would like to book an appointment.'),
    ('bundle', 26, 1, 'Why should we hire you and not the next person?', 'You should hire me because ___.'),
    ('bundle', 26, 2, 'What can you start helping with in week one?', 'In week one I can ___.'),
    ('bundle', 26, 3, 'What is one promise you can keep if we hire you?', 'You should hire me because ___.'),
    ('bundle', 27, 1, 'Someone misunderstood what you said. How do you clear it up?', 'Sorry, what I meant was ___.'),
    ('bundle', 27, 2, 'What do you say if it was your mistake?', 'Thanks for checking — let''s ___.'),
    ('bundle', 27, 3, 'How do you move the conversation forward?', 'Sorry, what I meant was ___.'),
    ('bundle', 28, 1, 'Tell me about yourself in 45 seconds.', 'To introduce myself, ___.'),
    ('bundle', 28, 2, 'What are you good at?', 'To introduce myself, ___.'),
    ('bundle', 28, 3, 'Why this field?', 'To introduce myself, ___.'),
    ('bundle', 29, 1, 'Pick a real situation from this week and talk for one minute.', 'This week I had to ___.'),
    ('bundle', 29, 2, 'What did you say, and what do you wish you had said?', 'Next time I will say ___.'),
    ('bundle', 29, 3, 'What will you try next time?', 'This week I had to ___.'),
    ('bundle', 30, 1, 'Introduce yourself.', 'In short, I can ___.'),
    ('bundle', 30, 2, 'Tell me about a real situation from this week.', 'In short, I can ___.'),
    ('bundle', 30, 3, 'Why should we hire you, in two sentences?', 'In short, I can ___.')
) as q(course_id, day_number, position, prompt, hint)
join public.course_days d
  on d.course_id = q.course_id and d.day_number = q.day_number
where not exists (
  select 1 from public.questions existing
  where existing.course_day_id = d.id and existing.position = q.position
);
